# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"headers": "Get.WikiAllAmerican.ipynb",
         "years": "Get.WikiAllAmerican.ipynb"}

modules = ["core.py"]

doc_url = "https://andrewt-cville.github.io/recruiting/"

git_url = "https://github.com/andrewt-cville/recruiting/tree/master/"

def custom_doc_links(name): return None
