# AUTOGENERATED! DO NOT EDIT! File to edit: j_notebooks/AllAmericanNotebook.ipynb (unless otherwise specified).

__all__ = []

# Cell
from bs4 import BeautifulSoup
import requests
import lxml
import time
import json