# AUTOGENERATED! DO NOT EDIT! File to edit: j_notebooks/Get.247-Team.ipynb (unless otherwise specified).

__all__ = ['headers', 'years']

# Cell
from bs4 import BeautifulSoup
import requests
import lxml
import time
import json

# Cell
headers={'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'}
years = ['2002', '2003', '2004', '2005', '2006', '2007', '2008', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
#HAVE TO MANUALLY GRAB 2009